name: Terraform Core Infra

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infra/core/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/core/**'

jobs:
  terraform-core:
    name: "Provision Core Infrastructure"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false # Tắt wrapper để tránh chèn log debug vào stdout

      - name: Terraform Init & Apply
        id: apply
        run: |
          cd infra/core
          terraform init
          terraform apply -auto-approve -no-color

          # 1. Lấy Private Key (Dùng EOF để xử lý nhiều dòng)
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_OUTPUT
          terraform output -raw ec2_private_key >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT # Đảm bảo có dòng trống cuối key
          echo "EOF" >> $GITHUB_OUTPUT

          # 2. Lấy Public IP (Lọc sạch chỉ lấy số và dấu chấm)
          IP=$(terraform output -raw ec2_public_ip | grep -E '^[0-9.]+$' | head -n 1)
          echo "PUBLIC_IP=$IP" >> $GITHUB_OUTPUT

      - name: Update GitHub Secrets (SSH Key)
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'SERVER_SSH_KEY'
          # Quan trọng: Dùng output từ bước apply phía trên
          value: ${{ steps.apply.outputs.PRIVATE_KEY }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }} 

      - name: Update Remote Host Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REMOTE_HOST'
          value: ${{ steps.apply.outputs.PUBLIC_IP }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}