name: Terraform Core Infra

on:
  # Cho phép kích hoạt thủ công từ giao diện GitHub Actions
  workflow_dispatch:
  
  # Tự động chạy khi có thay đổi trong thư mục core trên nhánh main
  push:
    branches: [ main ]
    paths:
      - 'infra/core/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/core/**'
jobs:
  terraform-core:
    name: "Provision Core Infrastructure"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Xác thực quyền với AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Thay bằng region của bạn

      # Cài đặt công cụ Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd infra/core
          terraform init

      - name: Terraform Plan
        run: |
          cd infra/core
          terraform plan

      # Thực thi tạo hạ tầng
      - name: Terraform Apply
        id: apply
        run: |
          cd infra/core
          terraform init
          terraform apply -auto-approve
          echo "PRIVATE_KEY=$(terraform output -raw private_key_pem)" >> $GITHUB_OUTPUT
          echo "PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      - name: Update GitHub Secrets
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'SERVER_SSH_KEY'
          value: ${{ steps.apply.outputs.PRIVATE_KEY }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }} 

      - name: Update Remote Host
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REMOTE_HOST'
          value: ${{ steps.apply.outputs.PUBLIC_IP }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}